namespace: dkube
repositories:
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: minio
  url: https://charts.min.io/

releases:
- chart: minio/minio
  name: minio
  values:
    - config/minio.yaml

- chart: grafana/loki
  name: loki
  values:
  - config/loki.yaml
- chart: grafana/promtail
  name: promtail
  values:
  - config/loki.yaml
- chart: grafana/tempo
  name: tempo
- chart: grafana/grafana
  name: grafana
  values:
  - config/grafana.yaml
- chart: prometheus-community/prometheus
  name: prometheus
  values:
    - kube-state-metrics:
        enabled: false
      prometheus-node-exporter:
        enabled: false
      prometheus-pushgateway:
        enabled: false
      alertmanager:
        enabled: false
- name: external-dns
  chart: oci://registry-1.docker.io/bitnamicharts/external-dns
  version: 8.7.5
  values:
  - sources:
    - ingress
    provider: cloudflare
    domainFilters: ["dkube.ai"]
    policy: sync
    cloudflare:
      apiToken: {{ requiredEnv "CF_API_TOKEN" }}
      proxied: false