namespace: dkube
repositories:
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: minio
  url: https://charts.min.io/
- name: jetstack
  url: https://charts.jetstack.io

releases:
- chart: minio/minio
  name: minio
  values:
    - config/minio.yaml

- chart: grafana/loki
  name: loki
  values:
  - config/loki.yaml
- chart: grafana/promtail
  name: promtail
  values:
  - config/loki.yaml
- chart: grafana/tempo
  name: tempo
- chart: grafana/grafana
  name: grafana
  values:
  - config/grafana.yaml
- chart: prometheus-community/prometheus
  name: prometheus
  values:
    - kube-state-metrics:
        enabled: false
      prometheus-node-exporter:
        enabled: false
      prometheus-pushgateway:
        enabled: false
      alertmanager:
        enabled: false
- name: external-dns
  chart: oci://registry-1.docker.io/bitnamicharts/external-dns
  version: 8.7.5
  values:
  - sources:
    - ingress
    provider: cloudflare
    domainFilters: ["dkube.ai"]
    cloudflare:
      apiToken: {{ requiredEnv "CF_API_TOKEN" }}
      proxied: false
- name: cert-manager
  chart: jetstack/cert-manager
  version: 1.17.1
  wait: true
  values:
  - crds:
      enabled: true
    extraArgs: ['--dns01-recursive-nameservers-only','--dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53', '--controllers=*,-certificaterequests-approver']
    deploymentAnnotations:
      certmanager.k8s.io/disable-validation: "true"

- name: certs
  chart: ./certs
  disableValidation: true
  jsonPatches:
  - target:
      kind: Secret
      name: cloudflare-api-token
    patch:
      - op: replace
        path: "/stringData/api-token"
        value: {{ requiredEnv "CF_API_TOKEN" }}
