postgres: 
  enabled: true
  db_user: postgres
  db_password: postgrespassword
db_url: postgresql://postgres:postgrespassword@postgresql
langfuse:
  enabled: true
  secret_key: lf_sk_x1234567890
  public_key: lf_pk_x1234567890
phoenix:
  enabled: false
litellm_master_key: "sk-1235"
litellm_model_list: []
imagePullSecrets: []
openwebui:
  image: ghcr.io/open-webui/open-webui
  tag: ""
  vector_db: chroma