postgres: 
  enabled: true
  db_user: postgres
  db_password: postgrespassword
db_url: postgresql://postgres:postgrespassword@postgresql
langfuse:
  enabled: true
  secret_key: lf_sk_x1234567890
  public_key: lf_pk_x1234567890
phoenix:
  enabled: false
litellm_master_key: "sk-1235"
litellm_model_list: []
imagePullSecrets: []
openwebui:
  image: ghcr.io/open-webui/open-webui
  tag: ""
  vector_db: chroma
  size: 2Gi
  tika: false
  pipeline_api_key: fake
storageClassName: ""
auth:
  name: Auth0
  domain: "oc-test.us.auth0.com"
  client_id: "XRGRuIU5ggf577nwGP9anLb28tC07H95"
  certificate: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlEQXpDQ0FldWdBd0lCQWdJSkd4bmhiczZWejljT01BMEdDU3FHU0liM0RRRUJDd1VBTUI4eEhUQWJCZ05WDQpCQU1URkc5akxYUmxjM1F1ZFhNdVlYVjBhREF1WTI5dE1CNFhEVEl3TURjd016QTBNRFV6TlZvWERUTTBNRE14DQpNakEwTURVek5Wb3dIekVkTUJzR0ExVUVBeE1VYjJNdGRHVnpkQzUxY3k1aGRYUm9NQzVqYjIwd2dnRWlNQTBHDQpDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzgzeFA1R0VjS1ZYT21qK1ZwejRIUTJldGxVWDZMDQoydHprbVZTUnRYcFNLNTZkSEp3UnNQS3prQjFoQ041eWFTMlYySUtnMGczZ1k5eXdKNlBzZ0ZJR1VVNCs3WDV0DQp5emxiblZMbTBLQlh6TXlINzZkWnRrc0l2eWFpYkppSnNVa1FCcUNXS2pocExiUlZPZzBiOGhTYWdvbTVKN0pKDQpTV2lVNDgvV2pOYVVXLzhpUVZUc3FpbmRINTZCSXBzVFNQc3V5LytsVDRleS9LSFpaVitSRVhSQ1MvREc4V2xFDQp1ajJpSWJyMHVjMTcxdzZZM004V25SRnR5MnEybkxjcXFNUDJWc0VCZFh0bTZsWERKeUZhZkFNMTJZNlE5UFlWDQpERjRwcjQvcHNQK25iRzRqSDdoZnRPd0JtTzlXRVZzWDZPTjM4U3dvaU1Qcks3ZHpENFhudFhuOUFnTUJBQUdqDQpRakJBTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRk83TnVsSXFwWG9iRjRoWWVIWFVacUNFDQp0OXpqTUE0R0ExVWREd0VCL3dRRUF3SUNoREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBTSsvMk5Ua0ROZWV1DQpIMWFveXlUTHVrUjJSVkRBS25rNFVWZTY4NVJGNUNienRQMzFOdHRZNnRtWUdtZjN0dXh3YTRMQlJDYTg1WE9ZDQpLOUNCbjlJcWpQdGlvSkhlS3VKYmpyNTVlTVNGay9OUGlOZWdRb1NScy9zSG1Va29Oc0ZXVmFyak5sMVgvTXl5DQpYb2Nna3RET0hIRUxld0ZIamZDcHY1SHNsMG5ieThOaUk4SyszcDJwY1pabGc1NXJnQXorZ1JOUngyTlBQZGFpDQptSWdCYzFWQmU3cDFNS0ZLaXVJYWRMQ2dhc1NoYXdwdFQxT0wzL3BXUUlvQlIzcDRhQzNHN3pKYUx3b0xVRmlUDQpXWEZNT29UUVdkSy9PcXhiUGZ4OEFsUjJvVHZ1NEphQVAvK0ZQTCtVOVNtSWFpMlRrcGQydDVLVis0TWR0TEVpDQptalEyWk1RMjN3PT0NCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
