environments:
  default:
    values:
    - ./config/default.yaml
    - ./config/{{.Namespace}}.yaml

---
repositories:
  - name: openwebui
    url: https://helm.openwebui.com/

  - name: litellm
    url: oci://ghcr.io/berriai/litellm-helm
    oci: true

  - name: langfuse
    url: https://langfuse.github.io/langfuse-k8s
    oci: false

  - name: homepage
    url: https://jameswynn.github.io/helm-charts

  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

  - name: runix
    url: https://helm.runix.net

releases:
  - name: postgresql
    chart: oci://registry-1.docker.io/bitnamicharts/postgresql
    version: 16.4.7
    namespace: {{ .Namespace }}
    condition: postgres.enabled
    values:
      - ./config/postgres.yaml.gotmpl

  - name: pgadmin
    chart: runix/pgadmin4
    namespace: {{ .Namespace }}
    condition: postgres.enabled
    values:
    - ./config/pgadmin4.yaml.gotmpl

  - name: openwebui
    chart: openwebui/open-webui
    namespace: {{ .Namespace }}
    values:
    - ./config/openwebui.yaml.gotmpl
  
  - name: litellm
    chart: oci://ghcr.io/berriai/litellm-helm
    version: 0.1.614
    namespace: {{ .Namespace }}
    values:
    - ./config/litellm.yaml.gotmpl

  - name: langfuse
    chart: langfuse/langfuse
    version: 0.12.1
    namespace: {{ .Namespace }}
    condition: langfuse.enabled
    values:
      - ./config/langfuse.yaml.gotmpl

  - name: homepage
    chart: homepage/homepage
    values:
    - ./config/homepage.yaml.gotmpl

  - name: cert
    chart: cert
    jsonPatches:
    - target:
        kind: Certificate
        name: dkube-ai
        namespace: {{ .Namespace }}
      patch:
        - op: replace
          path: "/spec/dnsNames/0"
          value: {{.Values.domain}}
        - op: replace
          path: "/spec/dnsNames/1"
          value: "*.{{.Values.domain}}"

  - name: nginx
    chart: ingress-nginx/ingress-nginx
    values:
    - config/ingress-nginx.gotmpl

  - name: grafana
    chart: ./external-service
    values:
      - name: grafana
        domain: {{.Values.domain}}
        port: 80
  - name: prometheus
    chart: ./external-service
    values:
      - name: prometheus-server
        domain: {{.Values.domain}}
        port: 80
  - name: minio
    chart: ./external-service
    values:
      - name: minio-console
        domain: {{.Values.domain}}
        port: 9001