adminUser: admin
adminPassword: hY9H9cEnFatxTGY2

# Static datasources
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        jsonData:
          timeout: 60
          maxLines: 1000
          httpHeaderName1: 'X-Scope-OrgID'
        secureJsonData:
          httpHeaderValue1: '1'
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server:80


dashboards:
  default:
    Logs:
      gnetId: 12611
      version: 2
      datasource: 
        - name: DS_PROMETHEUS
          value: Prometheus
        - name: DS_LOKI
          value: Loki



dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: false
        options:
          path: /var/lib/grafana/dashboards/default