kind: Service
apiVersion: v1
metadata:
  name: phoneix
spec:
  selector:
    app: phoenix
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 6006
    targetPort: 6006
    name: http
  - protocol: TCP
    port: 4317
    targetPort: 4317
    name: grpc