apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dkube-ai
spec:
  secretName: dkube-ai-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - "internal.dkube.ai"
    - "*.internal.dkube.ai"